day01.jar: day01.kt
	kotlinc $< -include-runtime -d $@

day01: day01.jar
	java -ea -jar $<

day02.jar: day02.kt
	kotlinc $< -include-runtime -d $@

day02: day02.jar
	java -ea -jar $<

day03.jar: day03.kt
	kotlinc $< -include-runtime -d $@

day03: day03.jar
	java -ea -jar $<
